name: Lazyloader
author: sppericat
category: Interface
tags: [lazyload, UI]
docs: http://github.com/stephanepericat/Lazyloader/blob/master/README.md
demo: http://sppericat.kodingen.com/demos/lazyloader/